import  Head  from 'next/head';
import styles from './MainLayout.module.css'
import { Navbar } from '../navBar/Navbar';

export const MainLayout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Rita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>
        { children }
      </main>
    </div>
  )
}